version: "3.9"

networks:
  cloudlab-network:

services:
  api:
    build: api
    hostname: api
    container_name: todo-api
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: floppa_is_the_best
      MYSQL_DATABASE: tododb
      MYSQL_USER: user
      MYSQL_PASSWORD: bingus
      MYSQL_HOST: mariadb

    ports:
      - "8080:8080"
    networks:
      - cloudlab-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: floppa_is_the_best
      MYSQL_DATABASE: tododb
      MYSQL_USER: user
      MYSQL_PASSWORD: bingus
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - cloudlab-network
