name: Push our app to GitHub registry

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO_NAME: ghcr.io/mario-pz/

jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build ./web -t ${{ env.REPO_NAME }}/todo-guru-web:${GITHUB_REF##*/}
      
      - name: Push the Docker image
        run: docker push  ${{ env.REPO_NAME }}/todo-guru-web:${GITHUB_REF##*/}


  build-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build ./api -t ${{ env.REPO_NAME }}/todo-guru-api:${GITHUB_REF##*/}
      
      - name: Push the Docker image
        run: docker push  ${{ env.REPO_NAME }}/todo-guru-api:${GITHUB_REF##*/}

