name: Push our app to GitHub registry

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image 1
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: mario-z/todo-guru-web:latest

  build-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image 2
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: mario-pz/todo-guru-api:latest

      #      - name: Build the Docker image
      #  run: docker build . --file infra/docker/Dockerfile -t ${{ env.IMAGE_NAME }}:${GITHUB_REF##*/}
      # - name: Push the Docker image
      #  run: docker push ${{ env.IMAGE_NAME }}:${GITHUB_REF##*/}
